/**
 * Media storage abstraction (PHASE C).
 *
 *   CMS -> media service -> MediaStorageProvider -> local disk | (S3 / R2)
 *
 * Only the media service talks to a provider; React components and routes
 * never touch filesystem paths or storage SDKs. Keys are generated by the
 * server (never from user input) and are validated again here.
 *
 * MEDIA_STORAGE_PROVIDER selects the provider:
 *   "local" (default) — files on disk under MEDIA_LOCAL_DIR, served at /media.
 *     In production this directory must be a persistent, backed-up volume.
 *   "s3" (PHASE J) — any S3-compatible bucket (AWS S3, Cloudflare R2, …),
 *     see server/media/s3.ts; files are served from MEDIA_PUBLIC_BASE_URL.
 * Unknown values or incomplete S3 settings fail at startup instead of
 * silently storing somewhere unexpected.
 */

import fs from 'node:fs/promises';
import { constants as fsConstants } from 'node:fs';
import path from 'node:path';
import { randomUUID } from 'node:crypto';
import { S3StorageProvider, s3ConfigFromEnv } from './s3';

export interface MediaStorageProvider {
  readonly name: string;
  put(key: string, data: Buffer, contentType: string): Promise<void>;
  delete(key: string): Promise<void>;
  exists(key: string): Promise<boolean>;
  /** Readiness probe: verifies local writes or authenticated object-store bucket access. */
  healthCheck(): Promise<void>;
  /** Local directory to serve at /media, or null when files are served elsewhere (CDN/bucket). */
  readonly localRoot: string | null;
}

/** Storage keys look like 2026/09/<uuid>/w800.avif — lowercase, no traversal. */
const KEY_PATTERN = /^\d{4}\/\d{2}\/[a-f0-9-]{36}\/[a-z0-9-]+\.(?:jpg|png|webp|avif|gif|mp4|webm)$/;

export function assertValidKey(key: string): void {
  if (!KEY_PATTERN.test(key)) throw new Error('Invalid media storage key.');
}

export class LocalStorageProvider implements MediaStorageProvider {
  readonly name = 'local';
  readonly localRoot: string;

  constructor(root: string) {
    this.localRoot = path.resolve(root);
  }

  private resolve(key: string): string {
    assertValidKey(key);
    const full = path.resolve(this.localRoot, key);
    if (!full.startsWith(this.localRoot + path.sep)) throw new Error('Media key escapes the storage root.');
    return full;
  }

  async put(key: string, data: Buffer): Promise<void> {
    const full = this.resolve(key);
    await fs.mkdir(path.dirname(full), { recursive: true });
    await fs.writeFile(full, data, { flag: 'wx' }); // never overwrite an existing object
  }

  async delete(key: string): Promise<void> {
    const full = this.resolve(key);
    await fs.rm(full, { force: true });
    // Remove the per-upload folder once its last file is gone (rmdir only succeeds when empty).
    await fs.rmdir(path.dirname(full)).catch(() => undefined);
  }

  async exists(key: string): Promise<boolean> {
    try {
      await fs.access(this.resolve(key));
      return true;
    } catch {
      return false;
    }
  }

  async healthCheck(): Promise<void> {
    await fs.mkdir(this.localRoot, { recursive: true });
    await fs.access(this.localRoot, fsConstants.W_OK);
    // Permission bits alone cannot detect a read-only/full persistent volume.
    const probe = path.join(this.localRoot, `.readiness-${randomUUID()}`);
    try { await fs.writeFile(probe, 'ready', { flag: 'wx' }); }
    finally { await fs.rm(probe, { force: true }); }
  }
}

let provider: MediaStorageProvider | null = null;

export function mediaStorage(): MediaStorageProvider {
  if (provider) return provider;
  const name = (process.env.MEDIA_STORAGE_PROVIDER || 'local').trim().toLowerCase();
  if (name === 's3') {
    provider = new S3StorageProvider(s3ConfigFromEnv());
    return provider;
  }
  if (name !== 'local') {
    throw new Error(`MEDIA_STORAGE_PROVIDER "${name}" is not supported; use "local" or "s3".`);
  }
  provider = new LocalStorageProvider(process.env.MEDIA_LOCAL_DIR || 'storage/media');
  return provider;
}
