/**
 * Media storage abstraction (PHASE C).
 *
 *   CMS -> media service -> MediaStorageProvider -> local disk | (S3 / R2)
 *
 * Only the media service talks to a provider; React components and routes
 * never touch filesystem paths or storage SDKs. Keys are generated by the
 * server (never from user input) and are validated again here.
 *
 * MEDIA_STORAGE_PROVIDER selects the provider. "local" (default) is the only
 * provider implemented in this phase; an S3-compatible provider (AWS S3 /
 * Cloudflare R2) plugs into the same interface once credentials exist —
 * requesting it now fails at startup instead of silently storing locally.
 */

import fs from 'node:fs/promises';
import path from 'node:path';

export interface MediaStorageProvider {
  readonly name: string;
  put(key: string, data: Buffer, contentType: string): Promise<void>;
  delete(key: string): Promise<void>;
  exists(key: string): Promise<boolean>;
  /** Local directory to serve at /media, or null when files are served elsewhere (CDN/bucket). */
  readonly localRoot: string | null;
}

/** Storage keys look like 2026/09/<uuid>/w800.avif — lowercase, no traversal. */
const KEY_PATTERN = /^\d{4}\/\d{2}\/[a-f0-9-]{36}\/[a-z0-9-]+\.(?:jpg|png|webp|avif|gif|mp4|webm)$/;

export function assertValidKey(key: string): void {
  if (!KEY_PATTERN.test(key)) throw new Error('Invalid media storage key.');
}

export class LocalStorageProvider implements MediaStorageProvider {
  readonly name = 'local';
  readonly localRoot: string;

  constructor(root: string) {
    this.localRoot = path.resolve(root);
  }

  private resolve(key: string): string {
    assertValidKey(key);
    const full = path.resolve(this.localRoot, key);
    if (!full.startsWith(this.localRoot + path.sep)) throw new Error('Media key escapes the storage root.');
    return full;
  }

  async put(key: string, data: Buffer): Promise<void> {
    const full = this.resolve(key);
    await fs.mkdir(path.dirname(full), { recursive: true });
    await fs.writeFile(full, data, { flag: 'wx' }); // never overwrite an existing object
  }

  async delete(key: string): Promise<void> {
    const full = this.resolve(key);
    await fs.rm(full, { force: true });
    // Remove the per-upload folder once its last file is gone (rmdir only succeeds when empty).
    await fs.rmdir(path.dirname(full)).catch(() => undefined);
  }

  async exists(key: string): Promise<boolean> {
    try {
      await fs.access(this.resolve(key));
      return true;
    } catch {
      return false;
    }
  }
}

let provider: MediaStorageProvider | null = null;

export function mediaStorage(): MediaStorageProvider {
  if (provider) return provider;
  const name = (process.env.MEDIA_STORAGE_PROVIDER || 'local').trim().toLowerCase();
  if (name !== 'local') {
    throw new Error(`MEDIA_STORAGE_PROVIDER "${name}" is not implemented yet; use "local".`);
  }
  provider = new LocalStorageProvider(process.env.MEDIA_LOCAL_DIR || 'storage/media');
  return provider;
}
