import { Globe2, Share2, ShieldCheck, ChartNoAxesCombined, Radio } from 'lucide-react';

export const CATEGORY_PRESENTATION: Record<string, { title: string; short: string; description: string; icon: typeof Globe2; note?: string }> = {
  'Site identity': { title: 'Site identity', short: 'Identity', description: 'Keep your saved site name and description together.', icon: Globe2, note: 'These saved values do not automatically change the public header or page descriptions.' },
  'SEO & social defaults': { title: 'SEO & social defaults', short: 'SEO & social', description: 'Maintain your default sharing image and social handle.', icon: Share2, note: 'Defaults are stored for future integration. Current page metadata keeps its existing behavior.' },
  'Search engine verification': { title: 'Search engine verification', short: 'Verification', description: 'Verify site ownership with webmaster tools.', icon: ShieldCheck, note: 'Saved tokens are published in page HTML. Configuration does not confirm ownership with a provider.' },
  'Analytics & advertising': { title: 'Analytics & advertising', short: 'Analytics & ads', description: 'Set provider IDs for consent-based tracking and ads.', icon: ChartNoAxesCombined, note: 'Providers activate only under the existing runtime conditions and the visitor’s matching privacy consent. Clear an ID to disable that provider.' },
  IndexNow: { title: 'IndexNow', short: 'Indexing', description: 'Notify participating search engines about content changes.', icon: Radio, note: 'The key file is public by design. Notifications follow the existing runtime rules; they do not guarantee indexing.' },
};

export const FIELD_PRESENTATION: Record<string, { label: string; detail?: string; helper: string; help: string; placeholder: string; technical?: boolean; multiline?: boolean }> = {
  siteName: { label: 'Site name', helper: 'The name saved in site identity settings.', help: 'A short site name, up to 80 characters. Saving it does not automatically rename the public header.', placeholder: 'Sporting Spy' },
  siteDescription: { label: 'Site description', helper: 'A concise description, up to 300 characters.', help: 'Describe the publication in plain text. The existing public description behavior stays unchanged.', placeholder: 'Independent sports journalism, schedules and tournament guides.', multiline: true },
  defaultOgImage: { label: 'Default social image', detail: 'Image URL', helper: 'Use a supported image URL or site path.', help: 'A saved default for social sharing. It is stored for future integration and does not currently replace page-specific images.', placeholder: 'https://example.com/social-image.jpg', technical: true },
  twitterHandle: { label: 'X / Twitter', detail: 'Handle', helper: 'Example: @SportingSpy', help: 'Your X / Twitter handle, including @. Up to 15 letters, digits or underscores after @. Stored for future integration.', placeholder: '@SportingSpy', technical: true },
  googleSiteVerification: { label: 'Google Search Console', detail: 'Verification token', helper: 'Paste the token from Google’s verification meta tag.', help: 'Use only the content value from the google-site-verification meta tag, not the entire tag. The saved token is published in page HTML.', placeholder: 'Google verification token', technical: true },
  bingSiteVerification: { label: 'Bing Webmaster Tools', detail: 'Verification token', helper: 'Paste the token from Bing’s verification meta tag.', help: 'Use only the content value from the msvalidate.01 meta tag. The saved token is published in page HTML.', placeholder: 'Bing verification token', technical: true },
  ga4MeasurementId: { label: 'Google Analytics 4', detail: 'Measurement ID', helper: 'Example: G-XXXXXXXXXX', help: 'Find the Measurement ID in your GA4 web data stream. Tracking requires the existing runtime conditions and the visitor’s analytics consent.', placeholder: 'G-XXXXXXXXXX', technical: true },
  adsensePublisherId: { label: 'Google AdSense', detail: 'Publisher ID', helper: 'Example: ca-pub-0000000000000000', help: 'Find your publisher ID in AdSense account information. Advertising requires the existing runtime conditions and the visitor’s advertising consent.', placeholder: 'ca-pub-0000000000000000', technical: true },
  indexNowKey: { label: 'IndexNow', detail: 'Key', helper: 'Use 8–128 letters, digits or dashes.', help: 'A key used to notify supported search engines about content changes. The key file is public by design; notifications do not guarantee indexing.', placeholder: 'Your IndexNow key', technical: true },
};
