import { Globe2, Share2, ShieldCheck, ChartNoAxesCombined, Radio } from 'lucide-react';

export const CATEGORY_PRESENTATION: Record<string, { title: string; short: string; description: string; icon: typeof Globe2; note?: string }> = {
  'Site identity': { title: 'Site identity', short: 'Identity', description: 'The public name and description of the site.', icon: Globe2, note: 'Changes appear on the public site on the next page load: header, footer, page titles, social previews and structured data. Leave empty to use the built-in SportingSpy branding.' },
  'SEO & social defaults': { title: 'SEO & social defaults', short: 'SEO & social', description: 'Default sharing image and X / Twitter handle.', icon: Share2, note: 'Used in social previews of every page that has no image of its own, and as the twitter:site account. Page-specific images always take priority.' },
  'Search engine verification': { title: 'Search engine verification', short: 'Verification', description: 'Verify site ownership with webmaster tools.', icon: ShieldCheck, note: 'Saved tokens are published in page HTML. Configuration does not confirm ownership with a provider.' },
  'Analytics & advertising': { title: 'Analytics & advertising', short: 'Analytics & ads', description: 'Set provider IDs for consent-based tracking and ads.', icon: ChartNoAxesCombined, note: 'Providers activate only under the existing runtime conditions and the visitor’s matching privacy consent. Clear an ID to disable that provider.' },
  IndexNow: { title: 'IndexNow', short: 'Indexing', description: 'Notify participating search engines about content changes.', icon: Radio, note: 'The key file is public by design. Notifications follow the existing runtime rules; they do not guarantee indexing.' },
};

export const FIELD_PRESENTATION: Record<string, { label: string; detail?: string; helper: string; help: string; placeholder: string; technical?: boolean; multiline?: boolean }> = {
  siteName: { label: 'Site name', helper: 'Shown in the header, footer, page titles and social previews.', help: 'A short site name, up to 80 characters. It replaces the built-in name in the public header and footer, default page titles, og:site_name and the Organization structured data. SEO titles an editor typed are kept as written.', placeholder: 'SportingSpy' },
  siteDescription: { label: 'Site description', helper: 'The default meta description and Organization description.', help: 'Plain text, up to 300 characters. Used as the default meta description and in the homepage Organization structured data. Pages with their own description keep it.', placeholder: 'Independent sports journalism, schedules and tournament guides.', multiline: true },
  defaultOgImage: { label: 'Default social image', detail: 'Image URL', helper: 'Use an https:// image URL or a site path.', help: 'Used as og:image / twitter:image on pages that have no image of their own (for example listing and legal pages). Page-specific and featured images always take priority.', placeholder: 'https://example.com/social-image.jpg', technical: true },
  twitterHandle: { label: 'X / Twitter', detail: 'Handle', helper: 'Example: @SportingSpy', help: 'Your X / Twitter handle, including @. Up to 15 letters, digits or underscores after @. Published as twitter:site on every page.', placeholder: '@SportingSpy', technical: true },
  googleSiteVerification: { label: 'Google Search Console', detail: 'Verification token', helper: 'Paste the token from Google’s verification meta tag.', help: 'Use only the content value from the google-site-verification meta tag, not the entire tag. The saved token is published in page HTML.', placeholder: 'Google verification token', technical: true },
  bingSiteVerification: { label: 'Bing Webmaster Tools', detail: 'Verification token', helper: 'Paste the token from Bing’s verification meta tag.', help: 'Use only the content value from the msvalidate.01 meta tag. The saved token is published in page HTML.', placeholder: 'Bing verification token', technical: true },
  ga4MeasurementId: { label: 'Google Analytics 4', detail: 'Measurement ID', helper: 'Example: G-XXXXXXXXXX', help: 'Find the Measurement ID in your GA4 web data stream. Tracking requires the existing runtime conditions and the visitor’s analytics consent.', placeholder: 'G-XXXXXXXXXX', technical: true },
  adsensePublisherId: { label: 'Google AdSense', detail: 'Publisher ID', helper: 'Example: ca-pub-0000000000000000', help: 'Find your publisher ID in AdSense account information. Advertising requires the existing runtime conditions and the visitor’s advertising consent.', placeholder: 'ca-pub-0000000000000000', technical: true },
  indexNowKey: { label: 'IndexNow', detail: 'Key', helper: 'Use 8–128 letters, digits or dashes.', help: 'A key used to notify supported search engines about content changes. The key file is public by design; notifications do not guarantee indexing.', placeholder: 'Your IndexNow key', technical: true },
};
